
Future getInternetData() async {
  await Future.delayed(Duration(seconds: 2));
  return 'Request completed successfully';
}

----- Async / Await ----

Future<void> main() async {
  print("Welcome to test page");

  try{
    var futureResponse = await getInternetData();
    print("Future response: $futureResponse");
  }catch(e){
    print("Response error: $e");
  }

  print("Executed after welcome!");

}

-------- âœ… Execution Output: --------

Welcome to test page
(Future waits 2 seconds)
Future response: Request completed successfully
Executed after welcome!

ðŸ‘‰ The execution waits before proceeding to the next line after await.



======= then / catchError =======

Future<void> main() async {
  print("Welcome to test page");

  getInternetData().then((responseData){
    print("Response data: $responseData");
  }).catchError((responseError){
    print("Response error: $responseError");
  });

  print("Executed after welcome!");

}


-------- âœ… Execution Output: --------

Welcome to test page
Executed after welcome!
(Future waits 2 seconds)
Response data: Request completed successfully


*** DIFFERENCE BETWEEN THE ABOVE 2 METHODS ***
- Async / await: The code is made to execute like a synchrnous code, it must complete executing the Future method before proceeding the print("Executed after welcome!");
- then / catchError: The Future is ran asynchrounously with the line of code, executes the then method after completing the Future process.